name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/main.yml

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          registry-url: https://registry.npmjs.org/
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: .
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}